### ISSUE TITLE
Script to run benchmark and add results

### ISSUE THREAD

**Issue by rick-heig** [inisis/katago-benchmark#2]
Hello, could you provide a script to run the benchmark so that users can report the performance with their hardware. This would allow to generate a comprehensive benchmark for multiple versions and multiple hardware configurations.

~I know this takes time and maybe you don't want to, but could you at least share the command you used to benchmark the cards on this repository.~ Thanks.

Edit : Sorry I just saw the commands are available in the README.
Is there a dockerfile for the docker image that is referred to in the "Docker" directory ?

**Comment by inisis** [comment]
Hi, I think this meets your needs, docker pull yaphets4desmond/katago:11.0.3-cudnn8-runtime-ubuntu18.04-tenosrrt8.0.0.3-opencl-stable

**Comment by rick-heig** [comment]
Thanks !
